# Generated by Django 5.2.8 on 2026-01-07 13:03

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.ticket_image_upload_path),
        ),
    ]
